# -*- coding: utf-8 -*-
"""wine predication ML (arun g)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14WeO6rirqGBeM7ay9mTvhbm-O_CHzrj5

**Wine Quality Predicition**

Objective :
The objective of the Project is to predict the quality of the wine using Wine.

DATA SOURCE :THE DATA OF THE WINES (DATA SET) IS TAKEN FROM THE GITHUB ACCOUNT OF YBI FOUNDATION ,IN THE RAW FORMAT.

**IMPORT** **LIBRARY**
"""

import pandas as pd

import numpy as np

"""**IMPORT** **DATA**"""

df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/WhiteWineQuality.csv',sep=';')

"""**Describe** **Data**"""

df.describe()

"""**Data** **Visualization**"""

df.head()

"""**DATA** **PREPROCESSING**"""

df.info()

df.columns

"""**Define Target Variable (y) and Feature Variables (X)**"""

y=df['quality']

y.shape

y

X=df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates',
      'alcohol']]

X=df.drop(['quality'],axis=1)

"""**TRAIN_TEST_SPLIT**"""

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y,random_state=2529)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

"""**MODELING**"""

from sklearn.svm import SVC

svc=SVC()

svc.fit(X_train,y_train)

"""**MODEL** **PREDICATION**"""

y_pred=svc.predict(X_test)

y_pred.shape

y_pred

"""**MODEL** **EVALUATION**"""

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

"""**EXPLAINATION:**
HERE WE CREATED A PROJECT OF WHITE WINE PREDICATION WSING ML FOR THIS PROJECT THE RESOURCE OF THE DATA IS THE DATASET GIVEN IN THE GITHUB ACCOUNT OF THE YBI FOUNDATION ,WE ALSO USED THE PANDAS LIBARAY ,SKLEARN LIBARAY FOR USING THE THINGS LIKE THE TRAIN_TEST_SPLIT ETC

THE QUICK STEPS ARE
IMPORT PYTHON LIBARIRES

IMPORT THE DATASETS

DISPLAY SOME DATA FROM THE DATASET IE THE HEAD ,INFO ,DESCRIBE,COLMNS ETC

DECLARE THE y AND X VARIABLES WHERE THE Y IS INDEPENDENT VARIABLE WHERE AS THE X IS A DEPENDENT VARIABLE

NOW USE SKLEARN MODEL FOR TRAIN_TEST_SPLIT

NOW PREDICT THE MODEL

NOW EVALUATE THE MODEL



"""

